services:

  backend:
    container_name: backend
    image: public.ecr.aws/c7o8u9c1/dvir-16:latest
    environment:
      DB_DIALECT: MYSQL
      DB_URL: jdbc:mysql://db:3306/lavagna?useUnicode=true
      DB_USER: root
      DB_PASS: 123456
      SPRING_PROFILE: dev
    ports:
      - 8080:8080
    entrypoint: ["bash", "entrypoint.sh"]
    depends_on:
      - db
    networks:
      - back-net
      - front-net

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lavagna
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-p123456", "lavagna"] # selecting lavagna database
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 2s
    ports:
      - 3306:3306
    volumes:
      - db-backup:/var/lib/mysql
      - ./src/main/resources/io/lavagna/db/MYSQL:/docker-entrypoint-initdb.d
      #- ./.travis.yml:/docker-entrypoint-initdb.d/:rw
    restart: unless-stopped
    networks:
      - back-net

  frontend:
    container_name: frontend
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./src/main/webapp:/usr/share/nginx/static #serving static content through vol
    ports:
      - 80:80
    networks:
      - front-net
    restart: unless-stopped

networks:
  front-net: #for frontend(nginx) service and backend 
  back-net: #for db(mysql) service and backend

volumes:
  db-backup: #a named vol to save localy database track of server interaction
